import {build} from 'esbuild';
import {createHash} from 'node:crypto';
import fs from 'node:fs/promises';
const result=await build({entryPoints:['app/flood-worker.ts'],bundle:true,write:false,format:'esm',platform:'browser',target:'es2022',minify:true});
const bytes=result.outputFiles[0].contents,hash=createHash('sha256').update(bytes).digest('hex').slice(0,12);
await fs.mkdir('public/workers',{recursive:true});
await fs.writeFile(`public/workers/flood-worker-${hash}.js`,bytes);
await fs.writeFile('app/worker-url.ts',`// Generated by scripts/build-worker.mjs. Always a same-origin public asset.\nexport const FLOOD_WORKER_URL = '/workers/flood-worker-${hash}.js';\n`);
console.log(`Flood worker ready: ${hash}`);
